### ISSUE TITLE
Request Deep virtual stereo odometry

### ISSUE THREAD

**Issue by CK-Sung** [yan99033/monodepth-cpp#13]
Hi, Great Works! 

Can you post reproduced code about the Deep Virtual Stereo Odometry as well, if you do not mind?

I would like to see that work as well !!

**Comment by yan99033** [comment]
Hi,

CNN-DSO is a good starting point if you are interested in DVSO
https://github.com/muskie82/CNN-DSO

On top of that, I have implemented colour image reader and undistorter (for Monodepth input), left-right consistency in the optimization, left and right disparities output in Monodepth-cpp. 

It would need some work to be ready for public use. If you have a partially implemented code and won't run properly, feel free to post it here for discussion.
