### ISSUE TITLE
Real world distance values?

### ISSUE THREAD

**Issue by antithing** [yan99033/monodepth-cpp#14]
Hi, and thank you for making this code available. This may be a stupid question, but will this code output real-world-scale distance values from the depth map? 

Or is it up-to-scale, as it is with monocular slam?

Thanks!

**Comment by yan99033** [comment]
The pre-trained models from Monodepth output metric depth (absolute distance in metre) after the scaling, i.e., 
depth = (focal_length * baseline) / (image_width * network_prediction)

**Comment by antithing** [comment]
Thank you! That's awesome.  I have a fisheye stereo pair that i would like to use this one, would i need to train a new model?

**Comment by yan99033** [comment]
The camera projection model for fisheye stereo pairs would be different from the pinhole projection model used in KITTI dataset. Therefore, you would need to train a new model.
