### ISSUE TITLE
tensorflow build error...

### ISSUE THREAD

**Issue by panyistory** [yan99033/monodepth-cpp#15]
We are currently building to try Monodepth.
The document says to use the version above "Tensorflow 1.6, CUDA 8.0, and cuDNN 6.0", the TensorFlow official document says to use bazel 0.9 in the "Tensorflow-GPU 1.6" version, and to use cudnn 7, cuda 9.
https://www.tensorflow.org/install/source#tested_build_configurations

Too many errors building the project above.
I'm building for a week now. Can you tell me the environment?

**Comment by yan99033** [comment]
Sorry for the late reply. I am working on a Docker container now, which is going to make it work regardless of your system environment. Stay tuned

**Comment by yan99033** [comment]
I have created a Docker container. You should be able to run it on your computer without a problem.
