### ISSUE TITLE
can we use models other than model_city2kitti?

### ISSUE THREAD

**Issue by naserpiltan** [yan99033/monodepth-cpp#19]
Hi @yan99033 
Im reading the original implementation of monodepth in you provided link .([https://github.com/mrharicot/monodepth](https://github.com/mrharicot/monodepth)).
In this repo , author provided some models checkpoint link that we can use in the original implementation.([http://visual.cs.ucl.ac.uk/pubs/monoDepth/models](http://visual.cs.ucl.ac.uk/pubs/monoDepth/models))
Now im planning to use this models in monodepth-cpp. I know that first should to freeze this checkpoints to a .pb frozen model.
I want to use resnet checkpoints in my monodepth-cpp app.
But i don't know  monodepth-cpp suppoorts resnet models directly or i have to to more things.
Please give me some idea.
Thank you.

**Comment by yan99033** [comment]
It definitely supports resnet model directly. 

It even supports other depth prediction model, too, if you know how to modify the code. The code essentially comprises loading the frozen model, inference, and post-processing.

**Comment by naserpiltan** [comment]
@yan99033  thank you sir. I got it .
I close this issue.
