### ISSUE TITLE
Should I install tensorflow in virtualenv method instead of source code method?

### ISSUE THREAD

**Issue by zxp771** [yan99033/monodepth-cpp#2]
Thanks for your sharing.
As the title said, I tried to install the tensorflow in virtualenv but it doesn't work when I compile the monodepth.
the error like this:

/home/zxp/monodepth-cpp-master/src/monodepth.cpp:30:41: fatal error: tensorflow/cc/ops/array_ops.h: No such file or directory
compilation terminated.
CMakeFiles/monodepth_static.dir/build.make:62: recipe for target 'CMakeFiles/monodepth_static.dir/src/monodepth.cpp.o' failed
make[2]: *** [CMakeFiles/monodepth_static.dir/src/monodepth.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/monodepth_static.dir/all' failed
make[1]: *** [CMakeFiles/monodepth_static.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Is this caused by the virtualenv method won't install the bazel?

**Comment by yan99033** [comment]
If you install Tensorflow using `pip install`, it won't work.

You need to build and install Tensorflow from source, [check this link](https://github.com/yan99033/monodepth-cpp/tree/master/Tensorflow_build_instructions) for instructions. Furthermore, you can find more information by clicking the links (under Reference) down below the page.

**Comment by zxp771** [comment]
@yan99033 
Thanks for your reply.
I have read your instruction. 
BTW for my GPU the drive for CUDA 9.0 is too old.
So I have to install CUDA in 10.0 and CUDNN in 7.4
I keep the bazel in 0.11.1.
Do these work for your code?

**Comment by yan99033** [comment]
Hi zxp711,

I don't think CUDA toolkit 10 will work. Tensorflow officially supports CUDA 9.0; you would need to downgrade your nvidia driver and install the compatible CUDA and cnDNN versions.

[Check out the Tensorflow link ](https://www.tensorflow.org/install/source#linux) to find out the compatible versions for CUDA, cuDNN, and Bazel tools.

**Comment by zxp771** [comment]
@yan99033 
Thanks for your suggestion.
I'll try it in cuda 9.0.
